### PR TITLE
JS update for tab index to fix WA issue with tabs

### PR DESCRIPTION
**Pull request by judaw**
WA Fixes for our expanders and tabs as a result of HR WA review. Completed with Sean's help.

Rec/req from Alison:
- [ ] Put this PR be put on a cddemo multidev, so we can review it IRL.
    * Update this PR description with "before and after" links, i.e. a link to an example page on cddemo dev and a link to an example page on a multidev with this branch.

Question from Alison:
* Do these changes belong in cwd_framework, **_then_** cwd_base?  (sincere question!)
  * If yes, do that, then start new PR over here.
  * P.S. Even if yes, whoever's doing the work can still create a multidev on cddemo and manually put the changes up there to help with testing and review!

### CODE REVIEW

**Comment by ama39** [comment]
It's hard to evaluate these without context, so please let me know if I am misunderstanding anything.

I think I understand what the Tabs commit is trying to fix. I see that for keyboard navigation (non-screen reader), there is a hidden focus target for the content tab after the navigation buttons, and this code is turning tabindex on and off to prevent that. If my understanding is correct, I think the fix is good but may be incomplete. It fixes it after a tab has been selected, but on page load, the hidden focus target is there until a button is activated by the user. So I think this is a good thing to fix, but recommend it be developed a little further to work on initial load as well.

For the Expander commit, I'm a little worried about applying a button role to the headings. I understand why such a change would be considered, but it's important to remember that the Expander is meant to work off of heading structure. So the headings are important to representing the content on the page, and one could argue that accessibility is reduced by removing their natural roles (especially since they are nested by heading level, so by making them all buttons, the nesting relationship is no longer communicated). With how attributes are used, the headings report to Voiceover as a "collapsed clickable heading" which is exactly what they are. Are we sure that changing them to buttons will be a net gain?

**Comment by sg667** [comment]
In regards to the expanders... the button role was intended to increase consistency of `aria-expanded`.  I will preface this by saying that more and more I have been utilizing HTML/ARIA official published specs to dictate if something is implemented correctly or not.

The reason I believe button is overall better for an expander is because of how `aria-expanded` is designed to be used.  [Official spec](https://www.w3.org/TR/wai-aria-1.2/#aria-expanded) states that `aria-expanded` can be used on the roles
- application
- button
- checkbox
- combobox
- gridcell
- link
- listbox
- menuitem
- row
- rowheader
- tab
- treeitem

What happens when aria-expanded is applied to a role not listed above will vary by screen reader/browser combo.  For instance, I have noticed that Chrome will *not* support `aria-expanded` on headings, both on Mac and PC screen readers.  However, it is supported on a `button` role, and because the functionality of the expander is consistent with what a button should do, I made the suggestion to apply `button` as the overriding role.

I believe a solution to headings on accordions would be to structure the accordions similar to the following in perhaps a future refresh of accordions (to probably be applied to new sites only, not retroactively).  This should announce the button, expanded/collapsed state, and heading level in conjunction across the board.  It should also ease up on the scripting because a native button doesn't need so many keyup listeners to run to make sure it toggles on Enter and Space.

```
<h3>
   <button aria-expanded="false">
      Title of accordion
   </button>
</h3>
<div class="accordion-panel-1">
.....
</div>
```

**Comment by ama39** [comment]
That sounds reasonable to me, and content contributors use the expander for a lot of different types of content that we can't predict. So maybe buttons are safer anyway, as long as there's no requirement regarding the length of button labels. A common use case is for FAQs, in which the "buttons" could be one or more sentences long. Normally, I like to see actual buttons have short text that clearly defines the action it will take.

In any case, you can consider me convinced! Applying a button role is fine, and the idea of a button tag inside the heading could be an interesting approach for a future version.

**Comment by alisonjo315** [comment]
Maybe someone could put this branch (or a combination of this branch and #62) on a `cddemo` multidev, so it can be reviewed IRL?

(Cross-posting on #62)

**Comment by alisonjo315** [comment]
I apologize if I'm off-base here or out of scope or whatever, I'm mediocre-at-best at using NVDA and my struggle could absolutely be me not the HR site -- but anyway:

While reviewing Engineering, I was trying to figure out how a main menu with drop-downs _**should**_ behave, and I remembered there was a lot of accessibility work done on the HR menu, so I tried it out, navigating with a screen reader and keyboard -- specifically NVDA, because I'm on Windows.

The audio prompt said "to navigate into this menu, press down arrow," but when I did that, it took me to the next top-level item in the main menu, not into the drop-down children (which is normal with NVDA, down/up arrow take you to the next thing on the page, so to speak).  When I pressed "enter" instead of down arrow, it took me to that page (i.e. I ended up on the "Your career" landing page, not inside the "Your career" sub menu).

Am I doing it wrong, or is there something wrong, or is this normal?

FWIW, when I'm not using NVDA, when I'm just navigating the HR site via keyboard, I can indeed use "down arrow" to enter the drop-down sub-menus of the main menu.

**Comment by alisonjo315** [comment]
I request that this PR be put on a `cddemo` multidev, so we can review it IRL.

Ideally, the PR would be updated with "before and after" links, i.e. a link to an example page on `cddemo` dev and a link to an example page on a multidev with this branch.

**Comment by alisonjo315** [comment]
@ama39  Is this PR superseded / rendered obsolete by the September 2023 snapshot?
https://github.com/CU-CommunityApps/cwd_base/commit/d2ca306789b9e46a7978cf452baba9d96307e4d4

I realize this PR deals with expanders *and* tabs... Here's what I think:
* If the "tabs" issues are still relevant, we'll need a new PR anyway, b/c there are conflicts due to the recent changes to expanders on the main branch.
  * **Question 1:** Are the "tabs" issues described in this PR still relevant?
* **Question 2:** Are any of the "expanders" issues described in this PR still relevant?
  * (If yes, we'll need a new PR -- but hopefully they're all set?????)

**Comment by sg667** [comment]
@alisonjo315 Regarding this PR - The changes outlined in Jan 2023 are definitely present on cwd_base.  We have headings with buttons inside and the buttons themselves do all the toggling.  This issue/PR can probably be closed out because it's not needed anymore.

**Comment by alisonjo315** [comment]
Ok great, thanks @sg667!

**Pull request closed without merging**
