### PR TITLE
Removing core-provided jQuery libraries

### PR DESCRIPTION
**Pull request by woodseowl**
Reference: Issue #1 
 
### Purpose
 - Removes jquery-ui 1.10.2 and jquery-ui-easing 1.11.0, as jquery.ui 1.12.1 is provided by Drupal core

### Review Steps
 - [ ] Code review to confirm jquery-ui-easing is not used in the base
 - [ ] Validate that jquery functions in the base theme still function as expected

### Notes
 - I was not sure where easing was used and code search didn't show any uses to me, so I hope that can just be dropped. I also didn't know if the code base uses any now-deprecated jquery methods, so I'm not sure where all to test. That said, it addressed the error I encountered in #1 and didn't introduce new errors.

### CODE REVIEW

**Comment by ama39** [comment]
Thanks for looking into this. jQuery's easing is used by some of our components (image gallery, card slider, and probably others), and potentially in the child themes for individual projects we've built. The About page of Office of Global Learning comes to mind, with its sticky nav. So we won't be able to simply remove it, unless it's all provided by Drupal (and everything remains compatible).

**Comment by woodseowl** [comment]
Cool. I will work on getting a proper test case that can be used to review the proposed changes.

**Comment by woodseowl** [comment]
Tone emailed:

In case it's helpful, here's an example snippet of jQuery UI Easing being used (taken from the sticky menu I made for OGL). It provides easing functions for use within jQuery's animated transitions ("easeInOutQuad" in this case):

image

**Comment by woodseowl** [comment]
@philwilliammee I added the core/jquery.ui dependency as suggested.

jQuery UI v1.12 provided by core has the easeInOutQuad easing Tone mentioned.

**Pull request merged**
